return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "chrome-debug-adapter",
        "clangd",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "css-lsp",
        "debugpy",
        "delve",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "gofumpt",
        "goimports",
        "gopls",
        "hadolint",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "prettier",
        "prettierd",
        "ruff",
        "ruff-lsp",
        "sql-formatter",
        "sqlfluff",
        "stylua",
        "tailwindcss-language-server",
        "tflint",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
