return require("packer").startup(function()
	use("wbthomason/packer.nvim")
	use("EdenEast/nightfox.nvim")
	use("kyazdani42/nvim-web-devicons")
	use("kyazdani42/nvim-tree.lua")
	use("neovim/nvim-lspconfig")
	use("hrsh7th/nvim-cmp") -- Autocompletion plugin
	use("hrsh7th/cmp-nvim-lsp") -- LSP source for nvim-cmp
	use("saadparwaiz1/cmp_luasnip") -- Snippets source for nvim-cmp
	use("L3MON4D3/LuaSnip") -- Snippets plugin
	use("onsails/lspkind-nvim")
	use("nvim-lua/plenary.nvim")
	use("nvim-telescope/telescope.nvim")
	use("rcarriga/nvim-notify")
	use("nvim-lualine/lualine.nvim")
	use("romgrk/barbar.nvim")
	use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
	use("nvim-treesitter/nvim-treesitter-refactor")
	use("williamboman/nvim-lsp-installer")
	use("jose-elias-alvarez/null-ls.nvim")
	use("terrortylor/nvim-comment")
	use("folke/which-key.nvim")
	use("akinsho/toggleterm.nvim")
	use("rose-pine/neovim")
	use("windwp/nvim-autopairs")
	use("norcalli/nvim-colorizer.lua")
	use("glepnir/dashboard-nvim")
	use("lewis6991/gitsigns.nvim")
	use("hrsh7th/vim-vsnip")
	use("RRethy/nvim-align")
	use("preservim/tagbar")
	use("folke/todo-comments.nvim")
	use("puremourning/vimspector")
	use({ "ms-jpq/coq_nvim", branch = "coq" })
	use({ "ms-jpq/coq.artifacts", branch = "artifacts" })
	use({ "ms-jpq/coq.thirdparty", branch = "3p" })
	use("ray-x/go.nvim")
	use("mfussenegger/nvim-dap")
	use("rcarriga/nvim-dap-ui")
	use("Pocco81/DAPInstall.nvim")
	use("danilo-augusto/vim-afterglow")
	use("romgrk/doom-one.vim")
	use("psliwka/termcolors.nvim")
	use("szw/vim-maximizer")
	use("catppuccin/nvim")
end)
