local set = vim.opt
vim.notify = require("notify")
vim.bo.expandtab = true
vim.bo.shiftwidth = 2
set.bo.softtabstop = 2
set.bo.smarttab = true
set.bo.tabstop = 2
set.hlsearch = true
set.incsearch = true
set.ignorecase = true
set.smartcase = true
set.wrap = false
set.scrolloff = 5
set.fileencoding = "utf-8"
set.termguicolors = true
set.relativenumber = true
set.cursorline = true
set.hidden = true
set.splitbelow = true
set.splitright = true
set.nu = true -- line numbers
set.completeopt = "menuone,noselect"
set.mouse = "a" -- enable mouse support
set.clipboard = "unnamedplus" -- copy/paste to system clipboard
set.swapfile = false -- don't use  a swapfile
vim.cmd("colorscheme rose-pine")
